import { z } from 'zod';

import { pluginManifestSchema } from './plugin-manifest.schema';

// Backend enforcement wrapper around the generated mirror of the canonical JSON schema
// (https://schemas.zenso.ink/v1/plugin-manifest.schema.json, which only requires
// id/schema_version/core_min/config_schema): the template build merges name/version
// from package.json but passes id from zenso.config.json through unvalidated, so the
// backend is the last gate guaranteeing id + SemVer version (+ non-empty name) that
// storage paths, asset URLs and version resolution depend on. Do not relax these.
//
// NOTE: plugin-manifest.schema.ts is 100% generated by scripts/generate-plugin-manifest.mjs
// and gets overwritten on every run — all hand-written strictness lives HERE, never there.
export const strictPluginManifestSchema = pluginManifestSchema.extend({
  id: z
    .string()
    .regex(new RegExp('^[a-z0-9]+/[a-z0-9-]+$'))
    .describe('Unique plugin identifier in owner/repo form, e.g. "zenso/zenso-plugin-calendar".'),
  name: z.string().min(1).describe('Human-readable plugin name shown in the panel.'),
  version: z.string().regex(new RegExp('^\\d+\\.\\d+\\.\\d+$')).describe('Plugin version (SemVer X.Y.Z).'),
});

export type StrictPluginManifest = z.infer<typeof strictPluginManifestSchema>;
